name: News_Feed
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  stylish_bottom_bar: ^1.0.3
  # html: ^0.15.4
  jsonml: ^0.1.9
  flutter_svg: ^2.0.5
  xml2json: ^5.3.6
  flutter_inappwebview: ^5.7.2+3
  skeleton_animation: ^0.1.4
  network_to_file_image: ^4.0.1
  fluttertoast: ^8.2.2
  flutter_signin_button: ^2.0.0
  firebase_core: ^2.16.0
  firebase_storage: ^11.2.7
  cloud_firestore: ^4.9.2
  provider: ^6.0.5
  http: ^0.13.6
  google_fonts: ^4.0.4
  firebase_auth: ^4.10.0
  shared_preferences: ^2.2.1
  google_sign_in: ^6.1.5
  font_awesome_flutter: ^9.2.0
  cupertino_icons: ^1.0.6
  url_launcher: ^6.1.11
  path_provider: ^2.1.1
  path: ^1.8.2
  flutter_file_dialog: ^3.0.2
  file_picker: ^5.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/categories/

  fonts:
      - family: Times
        fonts:
          - asset: assets/fonts/times_news_roman/Times New Roman 400.ttf
            weight: 400
          - asset: assets/fonts/times_news_roman/Times New Roman Gras 700.ttf
            weight: 700
      - family: Avenir
        fonts:
          - asset: assets/fonts/avenir/AvenirNextLTPro-Regular.otf
            weight: 400
          - asset: assets/fonts/avenir/AvenirNextLTPro-Demi.otf
            weight: 500
          - asset: assets/fonts/avenir/AvenirNextLTPro-Demi.otf
            weight: 600
          - asset: assets/fonts/avenir/avenir-next-lt-pro-bold.otf
            weight: 700
      - family: League
        fonts:
          - asset: assets/fonts/league_spartan/LeagueSpartan-Bold.otf
      - family: Stencil
        fonts:
          - asset: assets/fonts/Stencil/Stencil_Regular.ttf
            weight: 400
          - asset: assets/fonts/Stencil/StencilBT-Regular.otf
            weight: 700
      - family: Bookman
        fonts:
          - asset: assets/fonts/bookman/BOOKOS.ttf
            weight: 400
          
