// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxab1T9sxzAwsExKmHBIzqew0WN4P2gtA',
    appId: '1:842329593125:android:95f68e8ef27aad5b2536cc',
    messagingSenderId: '842329593125',
    projectId: 'newsfeed-ae077',
    storageBucket: 'newsfeed-ae077.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZmNubnWtehcM84vb2fsv2c0n98DlgeF0',
    appId: '1:842329593125:ios:714b15c19769fded2536cc',
    messagingSenderId: '842329593125',
    projectId: 'newsfeed-ae077',
    storageBucket: 'newsfeed-ae077.appspot.com',
    androidClientId: '842329593125-8gikoov4qmt9tpoqdufeg4hpv39igesc.apps.googleusercontent.com',
    iosClientId: '842329593125-3llqfcpdu5a7djrqea5v89behvsd2dcg.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsfeed',
  );
}
