// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbXwgYh3aJlVOhF1v5IAdX0kayDl9yjBI',
    appId: '1:526854315913:android:cde16ffb436a6a3b3b4b58',
    messagingSenderId: '526854315913',
    projectId: 'newsfeed-1297',
    storageBucket: 'newsfeed-1297.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRKdfVHzLzKTsTMuFetj_zZDlBa0kCmCs',
    appId: '1:526854315913:ios:93f0e13a4c8cf1e73b4b58',
    messagingSenderId: '526854315913',
    projectId: 'newsfeed-1297',
    storageBucket: 'newsfeed-1297.appspot.com',
    androidClientId: '526854315913-kq9jk0pi4mlatds1f9vhtbvvu30dinf3.apps.googleusercontent.com',
    iosClientId: '526854315913-i87lo87r7e6l9lu0k4ur879pvmvvbpo1.apps.googleusercontent.com',
    iosBundleId: 'com.newsfeed.app',
  );
}
